// pages/resourcesData.js
export const RESOURCES_MENU_ITEMS = [
  { id: 'content_creation',    title: 'Content Creation',    image: '/images/resources/content_creation.jpg',    description: 'End-to-end content strategy, writing and production for web & marketing.' },
  { id: 'image_creation',      title: 'Image Creation',      image: '/images/resources/image_creation.jpg',      description: 'High-quality images, social visuals and banners created to brand specs.' },
  { id: 'avatar_creation',     title: 'Avatar Creation',     image: '/images/resources/avatar_creation.jpg',     description: 'Branded avatars for teams, clients and profiles.' },
  { id: 'blog',                title: 'Blog',                image: '/images/resources/blog.jpg',                description: 'Editorial blog content — long-form, SEO-first articles.' },
  { id: 'infographic',         title: 'Info Graphic',        image: '/images/resources/infographic.jpg',         description: 'Data-driven infographics for reports, social and presentations.' },
  { id: 'ebook',               title: 'E-Book',              image: '/images/resources/ebook.jpg',               description: 'Downloadable eBooks and branded white-label guides.' },
  { id: 'audiobook',           title: 'Audio-Book',          image: '/images/resources/audiobook.jpg',           description: 'Narrated versions of guides and long-form content.' },
  { id: 'playbook',            title: 'Play Book',           image: '/images/resources/playbook.jpg',            description: 'Operational playbooks and repeatable workflows.' },
  { id: 'articles',            title: 'Articles',            image: '/images/resources/articles.jpg',            description: 'Short/medium length articles for PR and thought leadership.' },
  { id: 'white_paper',         title: 'White Paper',         image: '/images/resources/white_paper.jpg',         description: 'In-depth industry white papers and research reports.' },
  { id: 'newsletter',          title: 'News Letter',         image: '/images/resources/newsletter.jpg',          description: 'Branded newsletters for subscribers and partners.' },
  { id: 'news_room',           title: 'News Room',           image: '/images/resources/newsroom.jpg',            description: 'Press releases and newsroom resources.' },
  { id: 'journalist',          title: 'Journalist',          image: '/images/resources/journalist.jpg',          description: 'Connections & briefings for media and journalist outreach.' },
  { id: 'case_studies',        title: 'Case Studies',        image: '/images/resources/case_studies.jpg',        description: 'Success stories and client case studies.' },
  { id: 'magazine',            title: 'Magazine',            image: '/images/resources/magazine.jpg',            description: 'Digital/print magazine design and content production.' },
  { id: 'animation_video',     title: 'Animation Video',     image: '/images/resources/animation_video.jpg',     description: '2D animation explainer videos and motion design.' },
  { id: 'cartoon_video',       title: 'Cartoon Video',       image: '/images/resources/cartoon_video.jpg',       description: 'Character-driven cartoon videos for brand storytelling.' },
  { id: '3d_animation',        title: '3D Animation Video',  image: '/images/resources/3d_animation.jpg',        description: '3D modelling and cinematic animations.' },
  { id: 'stories',             title: 'Stories',             image: '/images/resources/stories.jpg',             description: 'Short narrative pieces designed for social & web.' },
  { id: 'reports',             title: 'Reports',             image: '/images/resources/reports.jpg',             description: 'Structured reports and industry analysis.' },
  { id: 'guides',              title: 'Guides',              image: '/images/resources/guides.jpg',              description: 'How-to guides and step-by-step manuals.' },
  { id: 'library',             title: 'Library',             image: '/images/resources/library.jpg',             description: 'Centralised library of all downloadable assets.' },
  { id: 'glossary',            title: 'Glossary',            image: '/images/resources/glossary.jpg',            description: 'Definitions and short explainers for domain terms.' },
  { id: 'knowledge_bank',      title: 'Knowledge Bank',      image: '/images/resources/knowledge_bank.jpg',      description: 'Curated knowledge base across products & services.' },
  { id: 'resources',           title: 'Resources',           image: '/images/resources/resources.jpg',           description: 'All resources and downloadable assets.' },
  { id: 'podcast',             title: 'Podcast',             image: '/images/resources/podcast.jpg',             description: 'Audio shows & interviews with industry experts.' },
  { id: 'riles_note',          title: 'Riles Note',          image: '/images/resources/riles_note.jpg',          description: 'Internal notes and short-form insights (Riles Notes).' },
  { id: 'riles_archives',      title: 'Riles Archives',      image: '/images/resources/riles_archives.jpg',      description: 'Archive of past notes, versions and revisions.' },
  { id: 'document_centre',     title: 'Document Centre',     image: '/images/resources/document_centre.jpg',     description: 'Official documents, templates and forms.' },
];
